### ISSUE TITLE
Race condition: multiple ConversationV2 without context created at same second

### ISSUE THREAD

**Issue by nmalzieu** [xmtp/xmtp-js#232] opened 2022-12-05 09:25 UTC
Per this Discord conversation: https://discord.com/channels/831836269558235136/936623389664235590/1048225770612457492

I have been able to create multiple `ConversationV2` with the same `peerAddress` without context & conversation id.
This is a problem because now I'm not sure which one to use / show when doing `client.conversations.list()`

Example:

Sender address is 0x4496848684441C15A915fa9bF07D131155603253
Peer address is 0x60065964CE67c6286035bC4e1487C2a1d01B3dEd
On dev network

**Comment by mkobetic** [comment] 2022-12-05 14:42
Thank you for reporting this. I don't see an easy way to resolve the race condition itself, new conversations are committed to the network asynchronously, so running `newConversation` multiple times within a short timespan can definitely create this situation.

That said we'll definitely give this some more thought to see if we can make some improvements here.

**Comment by elisealix22** [comment] 2022-12-19 16:03
Just got out of a call with a potential partner where they were running into this race condition using a fork of https://github.com/xmtp/xmtp-quickstart-react specifically with conversations using `conversationId`s. Their ask was, is there a way to provide a way to look up if a convo exists within the sdk? We mentioned in the meantime they could store the conversations locally and only call `newConversation` if it doesn't already exist.

**Comment by neekolas** [comment] 2022-12-21 02:23
So, the topic ID is generated on the client. Publishing is idempotent, but only based on the hash of the content. The problem is that the content changes because of the salt on the cipher text. So, even the identical payload if encrypted twice in two separate clients it will result in a different message hash.

**Comment by neekolas** [comment] 2022-12-21 16:06
> these are manual retries happening from the user, not automated retries happening from the client? 

That's right. We do have automated retries for non 2XX status codes on publish. Those work fine and are idempotent.

> Separate thing to ask: I'm assuming check if the conversation already exists would be doing so based on the conversation participants and the conversation ID. That relies on the participant list of a conversation being static and unchanging, which won't be the case for groups. I'm assuming that for 1:1 conversations in the future, we intend for them to be singletons where you can't add additional participants ('canonical threads'), which is the case in other messaging apps.

That's right. It's reasonable to think of 1:1 conversations as singletons, unique based on conversation ID and participants. At least, that's the goal. We are clearly falling short in this case.

**Comment by neekolas** [comment] 2023-04-13 17:45
Will be solved once this goes in https://github.com/xmtp/xmtp-js/issues/316

**Closed by neekolas** 2023-04-13 17:45 UTC
Labels: bug, P2
