### ISSUE TITLE
Random empty conversations appear sometimes

### ISSUE THREAD

**Issue by polmaire** [xmtp/xmtp-js#263] opened 2023-01-24 09:16 UTC
Sometimes, for reasons that I ignore, new empty conversations are created on the network with people that I already have conversations with. It seems to be a network issue but I might be wrong.

I can provide examples of conversations if needed.

**Comment by neekolas** [comment] 2023-01-25 23:57
I've tracked down the origin of the errors to the `example-chat-react` app.

When a conversation with a `conversationId` is selected, the [AddressInput component is calling](https://github.com/xmtp-labs/xmtp-inbox-web/blob/main/components/AddressInput.tsx#L53) `client.conversations.newConversation(address)` with no conversationId. This has the effect of creating a new V2 conversation with no `conversationId` in the background. The Inbox app doesn't actually show the conversation, because it removes conversations with no messages, but the conversation still exists and causes issues in other apps.

@bhavya2611 @elisealix22 @daria-github  I think the right solution is a bit of a refactor of the AddressInput and RecipientControl. It's weird to me that the `AddressInput` is trying to create a new conversation at all (`newConversation` has had the potential to send invites since `v7.0`), and especially weird that it is doing so on every path change. Not quite sure where to move that logic to, but it feels like it belongs in a higher level component than `AddressInput`.

**Comment by neekolas** [comment] 2023-01-26 00:17
Steps to reproduce:

1. Go on Lenster and start a new conversation with a user you have not talked to before (either wallet <> wallet or profile <> profile)
2. Go to the Inbox app and click on that conversation
3. Check the network tab and you should see a call to `/publish`

**Comment by polmaire** [comment] 2023-01-26 10:06
Thank you Nicholas for these insights - let me know if I can be of any help
in the process of solving this issue!

Le jeu. 26 janv. 2023 à 01:17, Nicholas Molnar ***@***.***> a
écrit :

**Comment by polmaire** [comment] 2023-01-31 17:38
Hello everyone, it seems like @neekolas has an idea of solution for this problem - do you already have an idea on when it can be fixed? Thank you very much in advance!

**Comment by neekolas** [comment] 2023-01-31 17:52
We have merged a change to xmtp.chat that should prevent new empty conversations from being created. 

For existing conversations, my recommendation would be to hide any chats in your UI that do not have at least 1 message.

**Comment by polmaire** [comment] 2023-01-31 19:21
Hey Nicholas, thanks a lot for your answer - I did not know about the
change.
That's very good news !

About existing chats we'll handle it no worries.
Thank you very much

Le mar. 31 janv. 2023 à 18:52, Nicholas Molnar ***@***.***> a
écrit :

**Comment by neekolas** [comment] 2023-02-03 17:47
Think we can mark this as closed, and create a new issue if we find any other cases where empty conversations are being created inadvertently

**Closed by neekolas** 2023-02-03 17:47 UTC
